const Agent = require("../models/agent.model"); // Adjust the path if needed

const seedAgents = async () => {
	try {
		await Agent.bulkCreate([
			{
				user_id: 1,
				firstName: "John",
				lastName: "Doe",
				gender: "Male",
				dob: new Date("1985-06-15"),
				email: "john.doe@example.com",
				phone: "1234567890",
				address: "123 Main Street",
				state: "California",
				country: "USA",
				city: "Los Angeles",
				pincode: "90001",
				joiningDate: new Date("2020-01-01"),
				experience: "5 years",
				aadharCard: "john_aadhar_card.jpg",
				panCard: "john_pan_card.jpg",
				bankPassbook: "john_bank_passbook.jpg",
				bankName: "Bank of America",
				branchName: "Downtown Branch",
				name: "John Doe",
				accountNumber: "123456789012",
				reEnterAccountNumber: "123456789012",
				ifscCode: "BOFA0001234",
				bankAddress: "456 Financial Street, Los Angeles",
				monthly_target: 5000.0,
				quarterly_target: 15000.0,
				yearly_target: 60000.0,
			},
			{
				user_id: 2,
				firstName: "Jane",
				lastName: "Smith",
				gender: "Female",
				dob: new Date("1990-02-25"),
				email: "jane.smith@example.com",
				phone: "9876543210",
				address: "456 Elm Street",
				state: "New York",
				country: "USA",
				city: "New York",
				pincode: "10001",
				joiningDate: new Date("2021-05-15"),
				experience: "3 years",
				aadharCard: "jane_aadhar_card.jpg",
				panCard: "jane_pan_card.jpg",
				bankPassbook: "jane_bank_passbook.jpg",
				bankName: "Chase Bank",
				branchName: "Uptown Branch",
				name: "Jane Smith",
				accountNumber: "987654321098",
				reEnterAccountNumber: "987654321098",
				ifscCode: "CHAS0009876",
				bankAddress: "789 Money Avenue, New York",
				monthly_target: 7000.0,
				quarterly_target: 21000.0,
				yearly_target: 84000.0,
			},
			{
				user_id: 3,
				firstName: "Alice",
				lastName: "Johnson",
				gender: "Female",
				dob: new Date("1988-11-10"),
				email: "alice.johnson@example.com",
				phone: "2345678901",
				address: "789 Pine Road",
				state: "Texas",
				country: "USA",
				city: "Houston",
				pincode: "77001",
				joiningDate: new Date("2019-03-20"),
				experience: "6 years",
				aadharCard: "alice_aadhar_card.jpg",
				panCard: "alice_pan_card.jpg",
				bankPassbook: "alice_bank_passbook.jpg",
				bankName: "Wells Fargo",
				branchName: "Midtown Branch",
				name: "Alice Johnson",
				accountNumber: "567890123456",
				reEnterAccountNumber: "567890123456",
				ifscCode: "WF0001234",
				bankAddress: "101 Money Lane, Houston",
				monthly_target: 6000.0,
				quarterly_target: 18000.0,
				yearly_target: 72000.0,
			},
		]);
		console.log("Dummy agents inserted successfully!");
	} catch (error) {
		console.error("Error seeding agents:", error);
	}
};

// Run the seeder script
seedAgents();
